apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim-2
  namespace: rahul
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
