apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: rahul
spec:
  selector:
    app: node-app
  ports:
  - name: node-port
    port: 5000
    targetPort: 5000
  type: ClusterIP
