apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  namespace: rahul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: rahulsharma312/react-app:v1
        env:
        - name: API_URL
          value: http://node-app-service.rahul:5000/
        ports:
        - containerPort: 3000
        resources:
            limits:
                cpu: "100m"
                memory: "256Mi"
            requests:
                cpu: "50m"
                memory: "128Mi"
      nodeSelector:
        node-label: rahul-node
