apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  namespace: rahul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: rahulsharma312/react-app:v6
        imagePullPolicy: "Always"
        env:
        - name: REACT_APP_API_URL
          value: node-app-service.rahul:5000/
        ports:
        - containerPort: 80
        # resources:
        #     limits:
        #         cpu: "100m"
        #         memory: "256Mi"
        #     requests:
        #         cpu: "50m"
        #         memory: "256Mi"
      nodeSelector:
        node-label: rahul-node
