
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: rahul
spec:
  selector:
    app: react-app
  ports:
  - name: react-port
    port: 80
    targetPort: 3000
  type: ClusterIP
