apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-sa-binding
  namespace: rahul
subjects:
- kind: ServiceAccount
  name: readonly-sa
  namespace: rahul
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

